// Re-export program IDs from kora-light-client (canonical source of truth)
pub use kora_light_client::program_ids::{
    ACCOUNT_COMPRESSION_AUTHORITY_PDA, ACCOUNT_COMPRESSION_PROGRAM_ID, CPI_AUTHORITY_PDA,
    CPI_AUTHORITY_PDA_SEED, LIGHT_LUT_DEVNET, LIGHT_LUT_MAINNET, LIGHT_SYSTEM_PROGRAM_ID,
    LIGHT_TOKEN_PROGRAM_ID, NOOP_PROGRAM_ID, REGISTERED_PROGRAM_PDA, TRANSFER2_DISCRIMINATOR,
    WSOL_MINT,
};
